export const books = [
	{
		id: 'p-1',
		title: 'Learn Python the Hard Way',
		thumbnail: 'img/python/learn-python-the-hard-way.jpeg',
		price: 675,
		category: 'python',
	},
	{
		id: 'p-2',
		title: 'Dive into Python 3',
		thumbnail: 'img/python/dive-into-python-3.jpeg',
		price: 799,
		category: 'python',
	},
	{
		id: 'p-3',
		title: 'Head First Python',
		thumbnail: 'img/python/head-first-python.jpeg',
		price: 902,
		category: 'python',
	},
	{
		id: 'p-4',
		title: 'Python Crash Course',
		thumbnail: 'img/python/python-crash-course.jpeg',
		price: 2218,
		category: 'python',
	},
	{
		id: 'p-5',
		title: 'Effective Python',
		thumbnail: 'img/python/effective-python.jpeg',
		price: 855,
		category: 'python',
	},
	{
		id: 'p-6',
		title: 'Think Python',
		thumbnail: 'img/python/think-python.jpeg',
		price: 475,
		category: 'python',
	},
	{
		id: 'p-7',
		title: 'Python Cookbook',
		thumbnail: 'img/python/python-cookbook.jpeg',
		price: 1149,
		category: 'python',
	},
	{
		id: 'p-8',
		title: 'Fluent Python',
		thumbnail: 'img/python/fluent-python.jpeg',
		price: 675,
		category: 'python',
	},
	{
		id: 'j-1',
		title: 'Javascript for Kids',
		thumbnail: 'img/js/js-for-kids.jpeg',
		price: 675,
		category: 'javascript',
	},
	{
		id: 'j-2',
		title: 'Head First Javascript',
		thumbnail: 'img/js/head-first-javascript.jpeg',
		price: 675,
		category: 'javascript',
	},
	{
		id: 'j-3',
		title: 'Javascript Guide',
		thumbnail: 'img/js/javascript-the-definitive-guide.jpeg',
		price: 675,
		category: 'javascript',
	},
	{
		id: 'j-4',
		title: 'Javascript the Good Parts',
		thumbnail: 'img/js/javascript-the-good-parts.jpeg',
		price: 675,
		category: 'javascript',
	},
	{
		id: 'j-5',
		title: 'Javascript & Jquery',
		thumbnail: 'img/js/javascript-and-jquery.jpeg',
		price: 675,
		category: 'javascript',
	},
	{
		id: 'j-6',
		title: 'You Don\'t Know JS',
		thumbnail: 'img/js/you-don-t-know-js.jpeg',
		price: 675,
		category: 'javascript',
	},
	{
		id: 'j-7',
		title: 'Eloquent Javascript',
		thumbnail: 'img/js/eloquent-javascript.jpeg',
		price: 675,
		category: 'javascript',
	},
	{
		id: 'j-8',
		title: 'Programming JS Apps',
		thumbnail: 'img/js/programming-javascript-applications.jpeg',
		price: 675,
		category: 'javascript',
	},

]
